/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kamali.ofcgrep;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import javax.swing.JFrame;

class AppTest {
    @Test void appHasAGreeting() {
        JFrame classUnderTest = new MainFrm();
    }
}
